### ISSUE TITLE
Ansible Playbook for Generating Self-Signed Security Certificates.

### ISSUE THREAD

**Issue by tfrench93** [opendistro-for-elasticsearch/sample-code#215]
Hello,

My team has been working with ODFE for quite some time now, and because of this, I have created an Ansible Playbook that generates the root CA, node and admin certificates for getting up and running very quickly with ODFE. I know that there is a sample script in the docs that also generates these scripts, but with the playbook, you can predetermine the subject information for the certificates as opposed to being prompted to add them in at the command line. Thus, you only need to run the command to run the playbook and everything gets generated off of that one command. 

 I was just wondering if there was any desire to have this added to this project somewhere and if so, where/what repo would be the best place to add it? 

Thanks!

**Comment by debu99** [comment]
where is it?

**Comment by tfrench93** [comment]
@debu99 There is no PR for it yet as I do not know where would be the best place to put it. Additionally, it seems there is not much interest in the playbook, anyways.

**Comment by Jon-AtAWS** [comment]
Hi @tfrench93,

This repo contains sample code, so I think it would be an excellent place to host it! Please file a PFR and we can get it in here.

Thanks,

Jon
