### ISSUE TITLE
Import object API not working

### ISSUE THREAD

**Issue by caoxinlong** [opendistro-for-elasticsearch/sample-code#216]
Hi,
I manage to upload the saved object to Kibana using import object API **(https://{es_endpoint}/_plugin/kibana/api/saved_objects/_import?overwrite=true)**
And I also follow the elastic document call the api **(curl -X POST ${ImportSavedObjectsAPI} -u ${$ElasticUsername}:${ElasticPassword} -H "kbn-xsrf: true" -H "securitytenant: private" --form file=@${Filepath})**. It seem not any error return but cannot see updated visualizations from Kibana.
Furthermore I also try to using postman to call the api and provide header **Content-Type:multipart/form-data, securitytenant:private, kbn-xsrf: true**, and **Basic Auth with login Kibana username and password**, I alway can get response status code 200 with wrong response body, but also cannot see updated visualizations from Kibana.

**Comment by bbarani** [comment]
@caoxinlong, are you still experiencing this issue?

**Comment by Jon-AtAWS** [comment]
Hi @caoxinlong,

I'm closing old issues. Please let us know if you are continuing to experience this problem. You can post to https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10 for help.

Thanks,

Jon
