### ISSUE TITLE
Support for Mapper Annotated Text Plugin

### ISSUE THREAD

**Issue by gjunge** [opendistro-for-elasticsearch/sample-code#233]
In order to support entity enrichment coming from our NLP engine, we would like to use the Mapper Annotated Text plugin.

https://www.elastic.co/guide/en/elasticsearch/plugins/7.10/mapper-annotated-text-usage.html

Thank you
Gidon

**Comment by Jon-AtAWS** [comment]
Hi @gjunge,

Sorry for the delayed response. Would you please post this request to this forum: https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10

Thanks,

Jon
