### ISSUE TITLE
timelion code pane too small 

### ISSUE THREAD

**Issue by okvittem** [opendistro-for-elasticsearch/sample-code#240]
In opendistroforelasticsearch-kibana 1.12.0, the code pane is rendered too small to see the code if there is an error in the timelion script the first time you open a timelion graph in a particular dashboard. 

Circumvention is to place cursor in the pane and navigate blindly with down_arrow down to the code line and the do a ctrl-a ctrl-x to get the code. Correct the code in a external editor and paste i back, upon which the code pane is rendered with a good size. 

This is remembered in case of subsequent syntax errors in the same dashboard. Reintroducing the bug and logging in in a new browser the size of the pane still comes out fine. 
So the bug is probably in the initial behind the scenes conversion from old to new builtin timelion style.

**Comment by Jon-AtAWS** [comment]
hi @okvittem,

Sorry for the delayed response. Would you please re-ask your question in this forum: https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10?

Thanks,

Jon
