### ISSUE TITLE
create index pattern and Kibana discover 

### ISSUE THREAD

**Issue by kolsmin** [opendistro-for-elasticsearch/sample-code#243]
Hi, This is a message from kibana Discover screen: 

> Expand your time range 
> One or more of the indices you’re looking at contains a date field. Your query may not match anything in the current time range, or there may not be any data at all in the currently selected time range. You can try changing the time range to one which contains data.

I'm using opendistro-for-elasticsearch and kibana version 1.12.0 

create index with step from Dev Tools of kibana 

1. Create Policy 
```
PUT _opendistro/_ism/policies/rsc_index_delete
{
  "policy": {
    "description": "Delete Rsc Resource Data 4days",
    "default_state": "search",
    "states": [
      {
        "name": "search",
        "actions": [],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "5d"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [
          {
            "delete": {}
          }
        ],
        "transitions": []
      }
    ]
  }
}
```
2. Create Index Template
```
PUT _index_template/rsc_template_min
{
  "index_patterns" : ["min-rsc-*"],
  "priority": 0,
  "template": {
    "settings": {
      "opendistro.index_state_management.policy_id":"rsc_index_delete"
    },
    "mappings":{
     "properties":{
        "time":{
          "type":"date",
          "format":"yyyy-MM-dd-HH:mm:ss"
        },
        "host_name": {
          "type": "text"
        },
        "rsc_type":{
          "type":"text"
        },
        "cur":{
          "type":"long"
        },
        "unit":{
          "type":"text"
        }
      }
    }
  }
}
```
3. Create documents by script in busybox
```
% vi mem_insert.sh
#!/bin/bash
TERM_TIME=10

while true
do
    start_time=`date +%s.%N`
    DATETIME=`date +%Y-%m-%d-%H-%M`
    TIME=`date +%Y-%m-%d-%H:%M:%S`
    MEM_CUR_STRING=`cat /sys/fs/cgroup/memory/memory.usage_in_bytes`

    mem_cur_byte=$MEM_CUR_STRING

    let mem_cur_kbyte=mem_cur_byte/1000
    let mem_cur_mega=mem_cur_kbyte/1000

    # insert data
    curl -k -H "Content-Type: application/x-ndjson" \
    -u ${admin}:${password} \
    -XPOST https://odfe-opendistro-es-client-service.smlee:9200/min-rsc-$DATETIME/_doc?pretty -d \
    '{"time":"'$TIME'","host_name":"'$HOSTNAME'","rsc_type":"Memory","cur":"'$mem_cur_kbyte'","unit":"kbyte"}'

    end_time=`date +%s.%N`
    elapsed_time=`echo "$end_time - $start_time" | bc`
    stime=`echo "$elapsed_time - (($elapsed_time/60) * 60)" | bc`

    sleep_time=`echo "$TERM_TIME - $elapsed_time" | bc`
    # echo "sleep_time = $sleep_time"
    sleep $sleep_time
done
```

i'm run scripts and create index 
```
GET _cat/indices/min*?v
```
result:
![image](https://user-images.githubusercontent.com/47405340/107302656-fdd82c80-6ac0-11eb-9285-46cf0f732b1d.png)

create index pattern
![image](https://user-images.githubusercontent.com/47405340/107302942-7fc85580-6ac1-11eb-9468-0f5bdd72964a.png)

and discover of kibana
![image](https://user-images.githubusercontent.com/47405340/107303124-d2097680-6ac1-11eb-80fe-f5cf423e76ea.png)

changing the search time but same results

how can i resolve??

**Comment by Jon-AtAWS** [comment]
Hi @kolsmin, 

Sorry for the delayed response. Would you please re-ask your question in this forum: https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10?

One idea - I have had issues where the time zone of the data was forward in time with respect to the time zone in Kibana. In that case, the data is there in the "future", but Kibana's panels are all looking into the past. You can use absolute dates with an endpoint more than 24 hours ahead to catch everything.

Let us know if that works.

Jon
