### ISSUE TITLE
Dashboard Drilldown in Open Distro

### ISSUE THREAD

**Issue by JujuElk** [opendistro-for-elasticsearch/sample-code#248]
Hi,

It would be awesome if we have drilldown feature in Open Distro. Make possible to navigate through dashboards by clicking on data from visualizations placed inside dashboards. It will allow users to have a better comprehension of their data, and make dashboard more user friendly. The feature to easily open one dashboard from another dashboard by clicking on link that user set up in dashboard edition.

Thanks,
Julien

**Comment by Jon-AtAWS** [comment]
Hi @JujuElk,

Sorry this is bouncing around a bit. Would you please re-ask the question in this forum: https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10

Thank you,

Jon
