### ISSUE TITLE
Official docker repo

### ISSUE THREAD

**Issue by feng-tao** [opendistro-for-elasticsearch/sample-code#250]
I found https://hub.docker.com/r/opendistroforelasticsearch/opendistroforelasticsearch and https://hub.docker.com/r/amazon/opendistro-for-elasticsearch. Are they both maintained by the opendistro community? If not, which one is the official one?

**Comment by Jon-AtAWS** [comment]
Hi @feng-tao,

Would you please ask your question here: https://discuss.opendistrocommunity.dev/c/build/12. Someone will be able to answer.

Thanks and sorry for the delayed response!

Jon
