### ISSUE TITLE
vm.max_map_count

### ISSUE THREAD

**Issue by anwarsky** [opendistro-for-elasticsearch/sample-code#253]
I try to run opendistro via docker-compose with docker-compose.yml provided in https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/
but opendicsto not running because of 
`max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`
then I try to increase max vm.max_map_count inside host:
sysctl -w vm.max_map_count=262144
but getting error:
`sysctl: setting key "vm.max_map_count": Read-only file system`
Is there any way to run opendicsto via docker-compose

**Comment by Jon-AtAWS** [comment]
Hi @anwarsky,

Thanks for reaching out. You can get a response by posting to this forum: https://discuss.opendistrocommunity.dev/c/general-elasticsearch/10. You can definitely run via docker compose, our manual details the process here: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/.

I'm not the best with Docker, but `sysctl: setting key "vm.max_map_count": Read-only file system` looks like a problem with the docker or underlying filesystem. 

Jon
