### ISSUE TITLE
Where can I find the source code of elastic search?

### ISSUE THREAD

**Issue by asheshv** [opendistro-for-elasticsearch/sample-code#254]
Multiple versions of Elastic Search has already been release, but - we can't find the source code of it.
Are you also planning to make the source available for public, so that - they can also contribute to it?

**Comment by Jon-AtAWS** [comment]
Hi @asheshv,

Yes, we are planning to make the source code available. You can find information about the status of that and the fork in this Forum: https://discuss.opendistrocommunity.dev/c/forking-elasticsearch-kibana/50. 

Have a look there!

Jon
